import type { MenuData, Product } from "@/lib/types";

const PHOTO: Record<string, string> = {
  "Çilekli Magnolya": "/menu/cilekli-magnolya.png",
  "Oreo Magnolya": "/menu/oreo-magnolya.png",
  Profiterol: "/menu/profiterol.png",
  "Lotus Magnolya": "/menu/lotus-magnolya.png",
  "Dubai Magnolya": "/menu/dubai-magnolya.png",
  Tiramisu: "/menu/tiramisu.png",
  "Fıstıklı Royal": "/menu/fistikli-royal.png",
  "Meyvalı Royal": "/menu/meyvali-royal.png",
  "Lotus Cheesecake": "/menu/lotus-cheesecake.png",
  "Frambuaz Cheesecake": "/menu/frambuaz-cheesecake.png",
  "American Cape": "/menu/american-cape.png",
  "Rulo Sarma Çilekli": "photo-1464349095431-e9a21285b5f3",
  Brownie: "/menu/brownie.png",
  "Mini Brownie": "/menu/mini-brownie.png",
  "San Sebastian": "/menu/san-sebastian.png",
  "Bonin Cookie": "/menu/bonin-cookie.png",
  "Meyveli Tart": "/menu/cilekli-tart.png",
  "Kinder Cheesecake": "/menu/kinder-cheesecake.png",
  "Limon Cheesecake": "photo-1524351199678-941a58a3df50",
  "Paris Prest": "/menu/paris-prest.png",
  Frambuaz: "/menu/frambuaz.png",
  Pistashio: "/menu/pistachio.png",
  Rafaello: "/menu/rafaello.png",
  Ekler: "/menu/ekler.png",
  "Çikolatalı Muffin": "/menu/cikolatali-muffin.png",
  "Orman Meyveli Muffin": "/menu/orman-meyveli-muffin.png",
  Rasbary: "/menu/rasbary.png",
  "Patatesli Gül Böreği": "/menu/patatesli-gul-boregi.png",
  "Ispanaklı Gül Böreği": "/menu/ispanakli-gul-boregi.png",
  "Poğaça": "/menu/pogaca.png",
  "Tuzlu Mini Box": "/menu/tuzlu-mini-box.png",
  Margarita: "/menu/margarita.png",
  Akdeniz: "/menu/akdeniz-pizza.png",
  "Dört Peynirli": "/menu/dort-peynirli.png",
  Karışık: "/menu/karisik-pizza.png",
  "Dana Füme": "/menu/dana-fume-pizza.png",
  "Ton Balıklı": "/menu/ton-balikli-pizza.png",
  BBQ: "photo-1565299585323-38d6b0865b47",
  Gurme: "/menu/gurme-pizza.png",
  Hetsiban: "/menu/hetsiban-pizza.png",
  "Fettuccini Alfredo": "/menu/fettuccini-alfredo.png",
  Napoliten: "/menu/napoliten.png",
  "Pesto Soslu": "/menu/pesto-soslu.png",
  "Bolonez Soslu": "/menu/bolonez-soslu.png",
  "Çıtır Sepeti": "photo-1562967914-608f82629710",
  "Çıtır Tavuk": "photo-1626082927389-6cd097cdc6ec",
  "Parmak Patates": "photo-1573080496219-bb080dd4f877",
  "Elma Dilim Patates": "photo-1518013431117-eb1465fa5752",
  "Cheddar Soslu Patates": "photo-1576107232684-1279f390859f",
  "Sezar Tavuk Salata": "/menu/sezar-tavuk-salata.png",
  "Ton Balıklı Salata": "/menu/ton-balikli-salata.png",
  "Avokado Füme Salata": "/menu/avokado-fume-salata.png",
  "Akdeniz Salata": "/menu/akdeniz-salata.png",
  "Tam Tahıllı Sandviç": "/menu/tam-tahilli-sandvic.png",
  "Bonin Sandviç": "/menu/bonin-sandvic.png",
  "Focaccia Sandviç": "/menu/focaccia-sandvic.png",
  "Mısır Ekmekli Sandviç": "/menu/misir-ekmekli-sandvic.png",
  "Ciabatta Sandviç": "/menu/ciabatta-sandvic.png",
  "Üç Peynirli Sandviç": "/menu/uc-peynirli-sandvic.png",
};

function photoUrl(name: string) {
  const src = PHOTO[name];
  if (!src) return null;
  if (src.startsWith("/")) return src;
  return `https://images.unsplash.com/${src}?auto=format&fit=crop&w=480&h=480&q=70`;
}

let n = 0;
function item(
  name: string,
  ingredients: string,
  allergens: string[],
  kcal: number,
  portion: string,
  priceTl: number,
): Product {
  n += 1;
  const slug = name
    .toLowerCase()
    .replace(/[^a-z0-9ğüşıöçâîû ]/gi, "")
    .trim()
    .replace(/\s+/g, "-");
  return {
    id: `p-${n}`,
    slug: `${slug}-${n}`,
    name,
    description: ingredients,
    priceCents: priceTl * 100,
    imageUrl: photoUrl(name),
    allergens,
    energyKcal: kcal,
    portionNote: portion,
    ingredientsNote: ingredients,
    isAvailable: true,
  };
}

export const boninMenu: MenuData = {
  tenant: {
    id: "tenant-bonin",
    slug: "bonin",
    name: "BONİN",
    tagline: "Bakery & Eatery",
    slogan: "Günün en güzel anı",
    logoUrl: "/brand/logo-wordmark.png",
    address: "Ravilon · Üniversite\nKınıklı Mah. Süleyman Demirel Cd. No:70\n20160 Pamukkale / Denizli",
    hours: "Her gün 08:00 – 01:00",
    instagram: "https://www.instagram.com/bonin.tr/",
    mapsUrl:
      "https://www.google.com/maps/search/?api=1&query=Ravilon+K%C4%B1n%C4%B1kl%C4%B1+S%C3%BCleyman+Demirel+Cd+No+70+Pamukkale+Denizli",
    currency: "TRY",
    locale: "tr",
  },
  categories: [
    {
      id: "tatli",
      slug: "tatlilar",
      name: "Tatlılar",
      products: [
        item("Çilekli Magnolya", "Magnolya kreması, çilek, bisküvi kırıntısı", ["G", "S"], 504, "porsiyon", 305),
        item("Oreo Magnolya", "Magnolya kreması, sünger kek, Oreo bisküvi", ["G", "S", "Y", "So*"], 788, "porsiyon", 305),
        item("Profiterol", "Sünger kek, magnolya kreması, profiterol", ["G", "S", "Y"], 593, "porsiyon", 305),
        item("Lotus Magnolya", "Magnolya kreması, lotus kreması, lotus bisküvisi", ["G", "S"], 984, "porsiyon", 305),
        item("Fıstıklı Royal", "Süt, krema, bitter çikolata, yumurta, jelatin, antep fıstığı", ["S", "Y", "F", "J*"], 450, "porsiyon", 350),
        item("Meyvalı Royal", "Süt, krema, beyaz çikolata, yumurta, jelatin, badem", ["S", "Y", "F", "J*"], 450, "porsiyon", 315),
        item("Lotus Cheesecake", "Un, margarin, krema, labne, lotus kreması/kırıntısı", ["G", "S", "Y"], 600, "dilim", 320),
        item("Frambuaz Cheesecake", "Un, margarin, krema, labne, bisküvi kırıntısı, frambuaz dolgu", ["G", "S", "Y"], 750, "dilim", 320),
        item("American Cape", "Yumurta, bitter çikolata, ceviz, un", ["G", "S", "Y", "F"], 650, "porsiyon", 220),
        item("Rulo Sarma Çilekli", "Yumurta, un, pastacı kreması, çilek", ["G", "S", "Y"], 300, "dilim", 315),
        item("Brownie", "Tereyağı, bitter çikolata, yumurta, un", ["G", "S", "Y"], 1045, "porsiyon", 320),
        item("San Sebastian", "Labne, krema, süt, yumurta, un/nişasta", ["G", "S", "Y"], 710, "dilim", 350),
        item("Bonin Cookie", "Yumurta, toz fındık, un, çikolata damla", ["G", "S", "Y", "F"], 560, "porsiyon", 200),
        item("Meyveli Tart", "Un, yumurta, toz fındık, pastacı kreması, çilek", ["G", "S", "Y", "F"], 690, "adet", 310),
        item("Kinder Cheesecake", "Süt, yumurta, jelatin, labne, sütlü çikolata", ["S", "Y", "J*"], 350, "dilim", 320),
        item("Limon Cheesecake", "Süt, yumurta, jelatin, labne, bisküvi kırıntısı, limon", ["G", "S", "Y", "J*"], 440, "dilim", 320),
        item("Paris Prest", "Un, yumurta, pastacı kreması, antep fıstığı, çikolata", ["G", "S", "Y", "F"], 1050, "porsiyon", 300),
        item("Frambuaz", "Süt, krema, beyaz çikolata, yumurta, jelatin", ["S", "Y", "J*"], 550, "adet", 350),
        item("Pistashio", "Süt, krema, beyaz çikolata, yumurta, jelatin, fıstık", ["S", "Y", "F", "J*"], 400, "adet", 350),
        item("Rasbary", "Süt, krema, bitter çikolata, yumurta, jelatin", ["S", "Y", "J*"], 750, "adet", 320),
        item("Dubai Magnolya", "Magnolya kreması, çikolata, kadayıf, antep fıstığı", ["G", "S", "F"], 820, "porsiyon", 305),
        item("Tiramisu", "Mascarpone kreması, kahve, sünger kek, kakao", ["G", "S", "Y"], 610, "porsiyon", 305),
        item("Rafaello", "Beyaz çikolata, hindistan cevizi, badem", ["S", "F"], 420, "adet", 320),
        item("Mini Brownie", "Tereyağı, bitter çikolata, yumurta, un, krema", ["G", "S", "Y"], 520, "porsiyon", 220),
        item("Ekler", "Choux hamuru, pastacı kreması, bitter çikolata", ["G", "S", "Y"], 480, "adet", 100),
        item("Çikolatalı Muffin", "Kakao, çikolata, yumurta, un, badem", ["G", "S", "Y", "F"], 430, "adet", 195),
        item("Orman Meyveli Muffin", "Un, yumurta, orman meyvesi, reçel", ["G", "S", "Y"], 390, "adet", 195),
      ],
    },
    {
      id: "tuzlu",
      slug: "tuzlular",
      name: "Tuzlular",
      products: [
        item("Patatesli Gül Böreği", "Yufka, patates, baharat", ["G"], 280, "adet", 100),
        item("Ispanaklı Gül Böreği", "Yufka, ıspanak, peynir", ["G", "S"], 260, "adet", 100),
        item("Poğaça", "Un, tereyağı, zeytin veya kaşar", ["G", "S"], 210, "adet", 60),
        item("Tuzlu Mini Box", "Susamlı kandil simidi", ["G", "Su"], 340, "kutu", 195),
      ],
    },
    {
      id: "sandvic",
      slug: "sandvicler",
      name: "Sandviçler",
      products: [
        item("Tam Tahıllı Sandviç", "Tahıllı ekmek, domates, marul, beyaz peynir, dana jambon", ["G", "S"], 520, "adet", 240),
        item("Bonin Sandviç", "Domates, marul, beyaz peynir, cheddar, dana jambon", ["G", "S"], 540, "adet", 240),
        item("Focaccia Sandviç", "Pesto sos, marul, beyaz peynir, cheddar, salatalık, domates, dana jambon", ["G", "S"], 560, "adet", 260),
        item("Mısır Ekmekli Sandviç", "Mısır ekmeği, domates, marul, beyaz peynir, hindi füme", ["G", "S"], 510, "adet", 240),
        item("Ciabatta Sandviç", "Ciabatta ekmek, domates, marul, beyaz peynir, dana jambon", ["G", "S"], 530, "adet", 240),
        item("Üç Peynirli Sandviç", "Beyaz peynir, kaşar, cheddar, domates, marul", ["G", "S"], 480, "adet", 240),
      ],
    },
    {
      id: "pizza",
      slug: "pizzalar",
      name: "Pizzalar",
      products: [
        item("Margarita", "Pizza hamuru, mozzarella, domates, pizza sosu", ["G", "S"], 871, "porsiyon", 370),
        item("Akdeniz", "Hamur, mozzarella, zeytin, biber, beyaz peynir, fesleğen", ["G", "S"], 1055, "porsiyon", 410),
        item("Dört Peynirli", "Hamur, mozzarella, rokfor, cheddar, parmesan", ["G", "S"], 1230, "porsiyon", 450),
        item("Karışık", "Hamur, mozzarella, salam, sucuk, sosis, sebzeler, parmesan", ["G", "S"], 1265, "porsiyon", 470),
        item("Dana Füme", "Hamur, mozzarella, dana füme et, mantar, parmesan", ["G", "S"], 1249, "porsiyon", 500),
        item("Ton Balıklı", "Hamur, mozzarella, ton balığı, zeytin, mısır", ["G", "S", "B"], 1017, "porsiyon", 450),
        item("BBQ", "Hamur, mozzarella, tavuk, BBQ sos, soğan", ["G", "S"], 1168, "porsiyon", 470),
        item("Gurme", "Hamur, mozzarella, kavurma, dana/hindi füme et, biber", ["G", "S"], 1116, "porsiyon", 470),
        item("Hetsiban", "Hamur, mozzarella, dana sucuk, mantar, közlenmiş biber", ["G", "S"], 1110, "porsiyon", 470),
      ],
    },
    {
      id: "makarna",
      slug: "makarnalar",
      name: "Makarnalar",
      products: [
        item("Fettuccini Alfredo", "Makarna, tavuk, mantar, krema, parmesan", ["G", "S"], 898, "porsiyon", 370),
        item("Napoliten", "Makarna, napoliten sos, krema, parmesan", ["G", "S"], 526, "porsiyon", 340),
        item("Pesto Soslu", "Makarna, pesto sos, krema, parmesan", ["G", "S", "F*"], 1002, "porsiyon", 310),
        item("Bolonez Soslu", "Makarna, domates sos, dana kıyma, krema, parmesan", ["G", "S"], 791, "porsiyon", 410),
      ],
    },
    {
      id: "atistirmalik",
      slug: "atistirmalik",
      name: "Atıştırmalık",
      products: [
        item("Çıtır Sepeti", "Tavuk, mozzarella çubuk, cheddar topu, sosis, soğan halkası, parmak patates", ["G", "S"], 3025, "tabak", 400),
        item("Çıtır Tavuk", "Unlu kızartılmış tavuk, parmak patates", ["G*"], 2010, "porsiyon", 310),
        item("Parmak Patates", "Patates (kızartma)", ["G*"], 1080, "porsiyon", 200),
        item("Elma Dilim Patates", "Patates (kızartma)", ["G*"], 1050, "porsiyon", 230),
        item("Cheddar Soslu Patates", "Patates, cheddar sos", ["S", "G*"], 1195, "porsiyon", 230),
      ],
    },
    {
      id: "salata",
      slug: "salatalar",
      name: "Salatalar",
      products: [
        item("Sezar Tavuk Salata", "Tavuk, marul, domates, kruton, sezar sos", ["G", "S", "Y*"], 406, "porsiyon", 350),
        item("Ton Balıklı Salata", "Mevsim yeşillikleri, ton balığı, mısır, domates, zeytinyağı", ["B"], 368, "porsiyon", 330),
        item("Avokado Füme Salata", "Yeşillikler, avokado, et füme, mozzarella, parmesan", ["S"], 723, "porsiyon", 370),
        item("Akdeniz Salata", "Yeşillikler, domates, beyaz peynir, zeytinyağı", ["S"], 254, "porsiyon", 300),
      ],
    },
  ],
};
